name: Dockerfile Linting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3
        with:
          dockerfile: taskmasterd.Dockerfile
      - uses: hadolint/hadolint-action@v3
        with:
          dockerfile: supervisor.Dockerfile
