name: Dockerfile Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: taskmasterd.Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: supervisor.Dockerfile

